- id: org-mode-autoformat
  name: org-mode-autoformat
  description: "Autoformats org-mode files."
  entry: org-mode-autoformat.sh
  language: docker
  types: [file]
  files: \.org$
  minimum_pre_commit_version: 0.15.0
